"""baseline current schema

Revision ID: 0001_baseline
Revises:
Create Date: 2026-07-10 20:39:16.188649
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '0001_baseline'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_bet_strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ai_run_id', sa.String(length=64), nullable=False),
    sa.Column('race_id', sa.String(length=32), nullable=False),
    sa.Column('strategy_type', sa.String(length=64), nullable=False),
    sa.Column('main_axis', sa.JSON(), nullable=True),
    sa.Column('second_axis_candidates', sa.JSON(), nullable=True),
    sa.Column('main_opponents', sa.JSON(), nullable=True),
    sa.Column('wide_opponents', sa.JSON(), nullable=True),
    sa.Column('exclude_candidates', sa.JSON(), nullable=True),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('bet_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_bet_strategies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_bet_strategies_ai_run_id'), ['ai_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_bet_strategies_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_bet_strategies_race_id'), ['race_id'], unique=False)

    op.create_table('ai_horse_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ai_run_id', sa.String(length=64), nullable=False),
    sa.Column('race_id', sa.String(length=32), nullable=False),
    sa.Column('horse_no', sa.Integer(), nullable=False),
    sa.Column('horse_name', sa.String(length=255), nullable=False),
    sa.Column('python_rank', sa.Integer(), nullable=True),
    sa.Column('ai_rank', sa.Integer(), nullable=True),
    sa.Column('ai_action', sa.String(length=32), nullable=False),
    sa.Column('ai_adjust_score', sa.Float(), nullable=False),
    sa.Column('ai_reason', sa.Text(), nullable=False),
    sa.Column('ai_risk', sa.Text(), nullable=True),
    sa.Column('ai_bet_role', sa.String(length=64), nullable=False),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ai_run_id', 'race_id', 'horse_no', name='uq_ai_horse_evaluations_run_race_horse')
    )
    with op.batch_alter_table('ai_horse_evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_horse_evaluations_ai_action'), ['ai_action'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_horse_evaluations_ai_bet_role'), ['ai_bet_role'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_horse_evaluations_ai_rank'), ['ai_rank'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_horse_evaluations_ai_run_id'), ['ai_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_horse_evaluations_horse_name'), ['horse_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_horse_evaluations_horse_no'), ['horse_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_horse_evaluations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_horse_evaluations_race_id'), ['race_id'], unique=False)

    op.create_table('ai_prediction_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('race_id', sa.String(length=32), nullable=False),
    sa.Column('race_date', sa.Date(), nullable=True),
    sa.Column('ai_mode', sa.String(length=64), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('python_prediction_run_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('race_summary', sa.Text(), nullable=True),
    sa.Column('pace_prediction', sa.String(length=128), nullable=True),
    sa.Column('python_trust_level', sa.String(length=32), nullable=True),
    sa.Column('raw_request', sa.JSON(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_prediction_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_prediction_runs_ai_mode'), ['ai_mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_prediction_runs_python_prediction_run_id'), ['python_prediction_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_prediction_runs_race_date'), ['race_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_prediction_runs_race_id'), ['race_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_prediction_runs_status'), ['status'], unique=False)

    op.create_table('bet_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_run_id', sa.String(length=36), nullable=False),
    sa.Column('race_id', sa.String(length=32), nullable=False),
    sa.Column('race_date', sa.Date(), nullable=True),
    sa.Column('rank', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('bet_type', sa.String(length=64), nullable=False),
    sa.Column('strategy', sa.String(length=128), nullable=False),
    sa.Column('axis_horse_nos', sa.JSON(), nullable=True),
    sa.Column('opponent_horse_nos', sa.JSON(), nullable=True),
    sa.Column('combinations', sa.JSON(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('stake_per_point', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('max_race_amount', sa.Integer(), nullable=False),
    sa.Column('max_day_amount', sa.Integer(), nullable=False),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('skip_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prediction_run_id', 'race_id', 'bet_type', 'strategy', name='uq_bet_candidates_run_race_strategy')
    )
    with op.batch_alter_table('bet_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bet_candidates_bet_type'), ['bet_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_bet_candidates_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bet_candidates_prediction_run_id'), ['prediction_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bet_candidates_race_date'), ['race_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_bet_candidates_race_id'), ['race_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bet_candidates_rank'), ['rank'], unique=False)
        batch_op.create_index(batch_op.f('ix_bet_candidates_status'), ['status'], unique=False)

    op.create_table('bet_settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bet_candidate_id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.String(length=32), nullable=False),
    sa.Column('race_date', sa.Date(), nullable=True),
    sa.Column('is_hit', sa.Boolean(), nullable=False),
    sa.Column('payout_amount', sa.Integer(), nullable=False),
    sa.Column('stake_amount', sa.Integer(), nullable=False),
    sa.Column('profit_loss', sa.Integer(), nullable=False),
    sa.Column('roi', sa.Float(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('settled_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bet_candidate_id', name='uq_bet_settlements_candidate')
    )
    with op.batch_alter_table('bet_settlements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bet_settlements_bet_candidate_id'), ['bet_candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bet_settlements_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bet_settlements_race_date'), ['race_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_bet_settlements_race_id'), ['race_id'], unique=False)

    op.create_table('data_quality_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source_file', sa.String(length=512), nullable=True),
    sa.Column('race_id', sa.String(length=32), nullable=True),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_quality_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_quality_issues_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_quality_issues_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_quality_issues_race_id'), ['race_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_quality_issues_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_quality_issues_source_file'), ['source_file'], unique=False)

    op.create_table('final_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ai_run_id', sa.String(length=64), nullable=False),
    sa.Column('race_id', sa.String(length=32), nullable=False),
    sa.Column('horse_no', sa.Integer(), nullable=False),
    sa.Column('horse_name', sa.String(length=255), nullable=False),
    sa.Column('python_rank', sa.Integer(), nullable=True),
    sa.Column('python_score', sa.Float(), nullable=True),
    sa.Column('ai_rank', sa.Integer(), nullable=True),
    sa.Column('ai_adjust_score', sa.Float(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('final_rank', sa.Integer(), nullable=True),
    sa.Column('final_bet_role', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ai_run_id', 'race_id', 'horse_no', name='uq_final_predictions_run_race_horse')
    )
    with op.batch_alter_table('final_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_final_predictions_ai_run_id'), ['ai_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_final_predictions_final_bet_role'), ['final_bet_role'], unique=False)
        batch_op.create_index(batch_op.f('ix_final_predictions_final_rank'), ['final_rank'], unique=False)
        batch_op.create_index(batch_op.f('ix_final_predictions_horse_name'), ['horse_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_final_predictions_horse_no'), ['horse_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_final_predictions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_final_predictions_race_id'), ['race_id'], unique=False)

    op.create_table('horse_past_performances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_file', sa.String(length=512), nullable=False),
    sa.Column('source_sheet', sa.String(length=64), nullable=False),
    sa.Column('target_race_id', sa.String(length=32), nullable=False),
    sa.Column('past_race_id', sa.String(length=32), nullable=True),
    sa.Column('horse_name', sa.String(length=255), nullable=True),
    sa.Column('race_date', sa.Date(), nullable=True),
    sa.Column('race_name', sa.String(length=255), nullable=True),
    sa.Column('horse_no', sa.Integer(), nullable=True),
    sa.Column('finish_position', sa.Integer(), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('odds', sa.Float(), nullable=True),
    sa.Column('distance', sa.String(length=64), nullable=True),
    sa.Column('jockey', sa.String(length=128), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('horse_past_performances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_horse_past_performances_horse_name'), ['horse_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_horse_past_performances_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_horse_past_performances_past_race_id'), ['past_race_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_horse_past_performances_race_date'), ['race_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_horse_past_performances_source_file'), ['source_file'], unique=False)
        batch_op.create_index(batch_op.f('ix_horse_past_performances_source_sheet'), ['source_sheet'], unique=False)
        batch_op.create_index(batch_op.f('ix_horse_past_performances_target_race_id'), ['target_race_id'], unique=False)

    op.create_table('horses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('horses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_horses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_horses_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_horses_normalized_name'), ['normalized_name'], unique=False)

    op.create_table('job_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('race_date', sa.Date(), nullable=True),
    sa.Column('race_id', sa.String(length=32), nullable=True),
    sa.Column('force', sa.Boolean(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_runs_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_runs_race_date'), ['race_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_runs_race_id'), ['race_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_runs_status'), ['status'], unique=False)

    op.create_table('odds_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_file', sa.String(length=512), nullable=False),
    sa.Column('race_date', sa.Date(), nullable=False),
    sa.Column('racecourse', sa.String(length=64), nullable=False),
    sa.Column('race_no', sa.Integer(), nullable=False),
    sa.Column('horse_no', sa.Integer(), nullable=True),
    sa.Column('horse_name', sa.String(length=255), nullable=True),
    sa.Column('bet_type', sa.String(length=64), nullable=False),
    sa.Column('combination', sa.String(length=64), nullable=True),
    sa.Column('odds', sa.Float(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_file', 'race_date', 'racecourse', 'race_no', 'horse_no', 'bet_type', 'combination', name='uq_odds_snapshot_source_key')
    )
    with op.batch_alter_table('odds_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_odds_snapshots_bet_type'), ['bet_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_odds_snapshots_horse_name'), ['horse_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_odds_snapshots_horse_no'), ['horse_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_odds_snapshots_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_odds_snapshots_race_date'), ['race_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_odds_snapshots_race_no'), ['race_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_odds_snapshots_racecourse'), ['racecourse'], unique=False)
        batch_op.create_index(batch_op.f('ix_odds_snapshots_source_file'), ['source_file'], unique=False)

    op.create_table('prediction_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('race_date', sa.Date(), nullable=True),
    sa.Column('race_id', sa.String(length=32), nullable=True),
    sa.Column('prediction_version', sa.String(length=64), nullable=False),
    sa.Column('feature_version', sa.String(length=64), nullable=False),
    sa.Column('weight_version', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('source_file', sa.String(length=512), nullable=True),
    sa.Column('output_file', sa.String(length=1024), nullable=True),
    sa.Column('result_json_file', sa.String(length=1024), nullable=True),
    sa.Column('manifest_file', sa.String(length=1024), nullable=True),
    sa.Column('input_checksum', sa.String(length=64), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('matched_count', sa.Integer(), nullable=False),
    sa.Column('mismatch_count', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prediction_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prediction_runs_race_date'), ['race_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_runs_race_id'), ['race_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_runs_status'), ['status'], unique=False)

    op.create_table('race_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('race_days', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_race_days_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_race_days_race_date'), ['race_date'], unique=True)

    op.create_table('race_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.String(length=32), nullable=False),
    sa.Column('race_date', sa.Date(), nullable=True),
    sa.Column('source_file', sa.String(length=1024), nullable=True),
    sa.Column('finish_order', sa.JSON(), nullable=False),
    sa.Column('payout_amount', sa.Integer(), nullable=False),
    sa.Column('payout_type', sa.String(length=64), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', name='uq_race_results_race_id')
    )
    with op.batch_alter_table('race_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_race_results_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_race_results_race_date'), ['race_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_race_results_race_id'), ['race_id'], unique=False)

    op.create_table('races',
    sa.Column('race_id', sa.String(length=32), nullable=False),
    sa.Column('race_date', sa.Date(), nullable=True),
    sa.Column('race_number', sa.Integer(), nullable=True),
    sa.Column('venue', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('start_time', sa.String(length=32), nullable=True),
    sa.Column('course', sa.String(length=64), nullable=True),
    sa.Column('track_condition', sa.String(length=64), nullable=True),
    sa.Column('race_type', sa.String(length=64), nullable=True),
    sa.Column('race_class', sa.String(length=64), nullable=True),
    sa.Column('headcount', sa.Integer(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('race_id')
    )
    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_races_race_date'), ['race_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_races_race_id'), ['race_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_races_race_number'), ['race_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_races_venue'), ['venue'], unique=False)

    op.create_table('raw_file_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_name', sa.String(length=512), nullable=False),
    sa.Column('file_type', sa.String(length=64), nullable=False),
    sa.Column('race_date', sa.Date(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    with op.batch_alter_table('raw_file_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_file_records_checksum'), ['checksum'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_file_records_file_name'), ['file_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_file_records_file_type'), ['file_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_file_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_file_records_race_date'), ['race_date'], unique=False)

    op.create_table('review_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.String(length=32), nullable=False),
    sa.Column('race_date', sa.Date(), nullable=True),
    sa.Column('bet_candidate_id', sa.Integer(), nullable=True),
    sa.Column('prediction_run_id', sa.String(length=36), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('ai_vs_result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_notes_bet_candidate_id'), ['bet_candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_notes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_notes_prediction_run_id'), ['prediction_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_notes_race_date'), ['race_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_notes_race_id'), ['race_id'], unique=False)

    op.create_table('prediction_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_run_id', sa.String(length=36), nullable=False),
    sa.Column('race_id', sa.String(length=32), nullable=False),
    sa.Column('horse_no', sa.Integer(), nullable=False),
    sa.Column('horse_name', sa.String(length=255), nullable=False),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('win_odds', sa.Float(), nullable=True),
    sa.Column('place_odds', sa.Float(), nullable=True),
    sa.Column('prediction_rank', sa.Integer(), nullable=True),
    sa.Column('prediction_score', sa.Float(), nullable=True),
    sa.Column('estimated_in3_rate', sa.Float(), nullable=True),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('risk_flag', sa.Boolean(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_reason', sa.Text(), nullable=True),
    sa.Column('evaluation_reason', sa.Text(), nullable=True),
    sa.Column('feature_summary', sa.JSON(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prediction_run_id'], ['prediction_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prediction_run_id', 'race_id', 'horse_no', name='uq_prediction_results_run_race_horse_no')
    )
    with op.batch_alter_table('prediction_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prediction_results_horse_name'), ['horse_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_results_horse_no'), ['horse_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_results_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_results_prediction_rank'), ['prediction_rank'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_results_prediction_run_id'), ['prediction_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_results_race_id'), ['race_id'], unique=False)

    op.create_table('race_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.String(length=32), nullable=False),
    sa.Column('horse_id', sa.Integer(), nullable=True),
    sa.Column('horse_no', sa.Integer(), nullable=False),
    sa.Column('frame_no', sa.Integer(), nullable=True),
    sa.Column('horse_name', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('carried_weight', sa.Float(), nullable=True),
    sa.Column('jockey', sa.String(length=128), nullable=True),
    sa.Column('trainer', sa.String(length=128), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('win_odds', sa.Float(), nullable=True),
    sa.Column('place_odds', sa.Float(), nullable=True),
    sa.Column('prediction_rank', sa.Integer(), nullable=True),
    sa.Column('prediction_score', sa.Float(), nullable=True),
    sa.Column('estimated_in3_rate', sa.Float(), nullable=True),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.race_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'horse_no', name='uq_race_entries_race_horse_no')
    )
    with op.batch_alter_table('race_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_race_entries_horse_id'), ['horse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_race_entries_horse_name'), ['horse_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_race_entries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_race_entries_race_id'), ['race_id'], unique=False)

    op.create_table('race_quality_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('issue_count', sa.Integer(), nullable=False),
    sa.Column('red_count', sa.Integer(), nullable=False),
    sa.Column('yellow_count', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['races.race_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', name='uq_race_quality_status_race_id')
    )
    with op.batch_alter_table('race_quality_statuses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_race_quality_statuses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_race_quality_statuses_race_id'), ['race_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_race_quality_statuses_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race_quality_statuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_race_quality_statuses_status'))
        batch_op.drop_index(batch_op.f('ix_race_quality_statuses_race_id'))
        batch_op.drop_index(batch_op.f('ix_race_quality_statuses_id'))

    op.drop_table('race_quality_statuses')
    with op.batch_alter_table('race_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_race_entries_race_id'))
        batch_op.drop_index(batch_op.f('ix_race_entries_id'))
        batch_op.drop_index(batch_op.f('ix_race_entries_horse_name'))
        batch_op.drop_index(batch_op.f('ix_race_entries_horse_id'))

    op.drop_table('race_entries')
    with op.batch_alter_table('prediction_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prediction_results_race_id'))
        batch_op.drop_index(batch_op.f('ix_prediction_results_prediction_run_id'))
        batch_op.drop_index(batch_op.f('ix_prediction_results_prediction_rank'))
        batch_op.drop_index(batch_op.f('ix_prediction_results_id'))
        batch_op.drop_index(batch_op.f('ix_prediction_results_horse_no'))
        batch_op.drop_index(batch_op.f('ix_prediction_results_horse_name'))

    op.drop_table('prediction_results')
    with op.batch_alter_table('review_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_notes_race_id'))
        batch_op.drop_index(batch_op.f('ix_review_notes_race_date'))
        batch_op.drop_index(batch_op.f('ix_review_notes_prediction_run_id'))
        batch_op.drop_index(batch_op.f('ix_review_notes_id'))
        batch_op.drop_index(batch_op.f('ix_review_notes_bet_candidate_id'))

    op.drop_table('review_notes')
    with op.batch_alter_table('raw_file_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_file_records_race_date'))
        batch_op.drop_index(batch_op.f('ix_raw_file_records_id'))
        batch_op.drop_index(batch_op.f('ix_raw_file_records_file_type'))
        batch_op.drop_index(batch_op.f('ix_raw_file_records_file_name'))
        batch_op.drop_index(batch_op.f('ix_raw_file_records_checksum'))

    op.drop_table('raw_file_records')
    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_races_venue'))
        batch_op.drop_index(batch_op.f('ix_races_race_number'))
        batch_op.drop_index(batch_op.f('ix_races_race_id'))
        batch_op.drop_index(batch_op.f('ix_races_race_date'))

    op.drop_table('races')
    with op.batch_alter_table('race_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_race_results_race_id'))
        batch_op.drop_index(batch_op.f('ix_race_results_race_date'))
        batch_op.drop_index(batch_op.f('ix_race_results_id'))

    op.drop_table('race_results')
    with op.batch_alter_table('race_days', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_race_days_race_date'))
        batch_op.drop_index(batch_op.f('ix_race_days_id'))

    op.drop_table('race_days')
    with op.batch_alter_table('prediction_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prediction_runs_status'))
        batch_op.drop_index(batch_op.f('ix_prediction_runs_race_id'))
        batch_op.drop_index(batch_op.f('ix_prediction_runs_race_date'))

    op.drop_table('prediction_runs')
    with op.batch_alter_table('odds_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_odds_snapshots_source_file'))
        batch_op.drop_index(batch_op.f('ix_odds_snapshots_racecourse'))
        batch_op.drop_index(batch_op.f('ix_odds_snapshots_race_no'))
        batch_op.drop_index(batch_op.f('ix_odds_snapshots_race_date'))
        batch_op.drop_index(batch_op.f('ix_odds_snapshots_id'))
        batch_op.drop_index(batch_op.f('ix_odds_snapshots_horse_no'))
        batch_op.drop_index(batch_op.f('ix_odds_snapshots_horse_name'))
        batch_op.drop_index(batch_op.f('ix_odds_snapshots_bet_type'))

    op.drop_table('odds_snapshots')
    with op.batch_alter_table('job_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_runs_status'))
        batch_op.drop_index(batch_op.f('ix_job_runs_race_id'))
        batch_op.drop_index(batch_op.f('ix_job_runs_race_date'))
        batch_op.drop_index(batch_op.f('ix_job_runs_job_type'))

    op.drop_table('job_runs')
    with op.batch_alter_table('horses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_horses_normalized_name'))
        batch_op.drop_index(batch_op.f('ix_horses_name'))
        batch_op.drop_index(batch_op.f('ix_horses_id'))

    op.drop_table('horses')
    with op.batch_alter_table('horse_past_performances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_horse_past_performances_target_race_id'))
        batch_op.drop_index(batch_op.f('ix_horse_past_performances_source_sheet'))
        batch_op.drop_index(batch_op.f('ix_horse_past_performances_source_file'))
        batch_op.drop_index(batch_op.f('ix_horse_past_performances_race_date'))
        batch_op.drop_index(batch_op.f('ix_horse_past_performances_past_race_id'))
        batch_op.drop_index(batch_op.f('ix_horse_past_performances_id'))
        batch_op.drop_index(batch_op.f('ix_horse_past_performances_horse_name'))

    op.drop_table('horse_past_performances')
    with op.batch_alter_table('final_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_final_predictions_race_id'))
        batch_op.drop_index(batch_op.f('ix_final_predictions_id'))
        batch_op.drop_index(batch_op.f('ix_final_predictions_horse_no'))
        batch_op.drop_index(batch_op.f('ix_final_predictions_horse_name'))
        batch_op.drop_index(batch_op.f('ix_final_predictions_final_rank'))
        batch_op.drop_index(batch_op.f('ix_final_predictions_final_bet_role'))
        batch_op.drop_index(batch_op.f('ix_final_predictions_ai_run_id'))

    op.drop_table('final_predictions')
    with op.batch_alter_table('data_quality_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_quality_issues_source_file'))
        batch_op.drop_index(batch_op.f('ix_data_quality_issues_severity'))
        batch_op.drop_index(batch_op.f('ix_data_quality_issues_race_id'))
        batch_op.drop_index(batch_op.f('ix_data_quality_issues_id'))
        batch_op.drop_index(batch_op.f('ix_data_quality_issues_code'))

    op.drop_table('data_quality_issues')
    with op.batch_alter_table('bet_settlements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bet_settlements_race_id'))
        batch_op.drop_index(batch_op.f('ix_bet_settlements_race_date'))
        batch_op.drop_index(batch_op.f('ix_bet_settlements_id'))
        batch_op.drop_index(batch_op.f('ix_bet_settlements_bet_candidate_id'))

    op.drop_table('bet_settlements')
    with op.batch_alter_table('bet_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bet_candidates_status'))
        batch_op.drop_index(batch_op.f('ix_bet_candidates_rank'))
        batch_op.drop_index(batch_op.f('ix_bet_candidates_race_id'))
        batch_op.drop_index(batch_op.f('ix_bet_candidates_race_date'))
        batch_op.drop_index(batch_op.f('ix_bet_candidates_prediction_run_id'))
        batch_op.drop_index(batch_op.f('ix_bet_candidates_id'))
        batch_op.drop_index(batch_op.f('ix_bet_candidates_bet_type'))

    op.drop_table('bet_candidates')
    with op.batch_alter_table('ai_prediction_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_prediction_runs_status'))
        batch_op.drop_index(batch_op.f('ix_ai_prediction_runs_race_id'))
        batch_op.drop_index(batch_op.f('ix_ai_prediction_runs_race_date'))
        batch_op.drop_index(batch_op.f('ix_ai_prediction_runs_python_prediction_run_id'))
        batch_op.drop_index(batch_op.f('ix_ai_prediction_runs_ai_mode'))

    op.drop_table('ai_prediction_runs')
    with op.batch_alter_table('ai_horse_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_horse_evaluations_race_id'))
        batch_op.drop_index(batch_op.f('ix_ai_horse_evaluations_id'))
        batch_op.drop_index(batch_op.f('ix_ai_horse_evaluations_horse_no'))
        batch_op.drop_index(batch_op.f('ix_ai_horse_evaluations_horse_name'))
        batch_op.drop_index(batch_op.f('ix_ai_horse_evaluations_ai_run_id'))
        batch_op.drop_index(batch_op.f('ix_ai_horse_evaluations_ai_rank'))
        batch_op.drop_index(batch_op.f('ix_ai_horse_evaluations_ai_bet_role'))
        batch_op.drop_index(batch_op.f('ix_ai_horse_evaluations_ai_action'))

    op.drop_table('ai_horse_evaluations')
    with op.batch_alter_table('ai_bet_strategies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_bet_strategies_race_id'))
        batch_op.drop_index(batch_op.f('ix_ai_bet_strategies_id'))
        batch_op.drop_index(batch_op.f('ix_ai_bet_strategies_ai_run_id'))

    op.drop_table('ai_bet_strategies')
    # ### end Alembic commands ###
