"""add core history and ai analysis tables

Revision ID: 0002_core_history
Revises: 0001_baseline
Create Date: 2026-07-10 20:50:25.083601
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '0002_core_history'
down_revision: str | None = '0001_baseline'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('version_name', sa.String(length=120), nullable=False),
    sa.Column('environment', sa.String(length=30), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("environment IN ('production','research','development','test')", name='ck_config_versions_environment'),
    sa.CheckConstraint('length(sha256) = 64', name='ck_config_versions_sha256'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key', 'version_name', name='uq_config_versions_key_name'),
    sa.UniqueConstraint('sha256')
    )
    with op.batch_alter_table('config_versions', schema=None) as batch_op:
        batch_op.create_index('ix_config_versions_active', ['environment', 'is_active'], unique=False)
        batch_op.create_index('ix_config_versions_created_at', ['created_at'], unique=False)

    op.create_table('feature_weight_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('weight_key', sa.String(length=100), nullable=False),
    sa.Column('version_name', sa.String(length=120), nullable=False),
    sa.Column('weights_json', sa.JSON(), nullable=False),
    sa.Column('source_file_path', sa.Text(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(sha256) = 64', name='ck_feature_weight_versions_sha256'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256'),
    sa.UniqueConstraint('weight_key', 'version_name', name='uq_feature_weight_versions_key_name')
    )
    with op.batch_alter_table('feature_weight_versions', schema=None) as batch_op:
        batch_op.create_index('ix_feature_weight_versions_active', ['weight_key', 'is_active'], unique=False)
        batch_op.create_index('ix_feature_weight_versions_created_at', ['created_at'], unique=False)

    op.create_table('idempotency_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope', sa.String(length=150), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.JSON(), nullable=True),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=200), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('processing','completed','failed')", name='ck_idempotency_records_status'),
    sa.CheckConstraint('length(request_hash) = 64', name='ck_idempotency_records_hash'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'idempotency_key', name='uq_idempotency_records_scope_key')
    )
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.create_index('ix_idempotency_records_expiry', ['expires_at'], unique=False)
        batch_op.create_index('ix_idempotency_records_resource', ['resource_type', 'resource_id'], unique=False)

    op.create_table('bet_status_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('bet_candidate_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(length=30), nullable=True),
    sa.Column('new_status', sa.String(length=30), nullable=False),
    sa.Column('changed_by', sa.String(length=200), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("new_status IN ('draft','candidate','review_required','planned','purchased','awaiting_result','settled','skipped','cancelled','blocked')", name='ck_bet_status_history_new_status'),
    sa.ForeignKeyConstraint(['bet_candidate_id'], ['bet_candidates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bet_status_history', schema=None) as batch_op:
        batch_op.create_index('ix_bet_status_history_bet_time', ['bet_candidate_id', 'created_at'], unique=False)
        batch_op.create_index('ix_bet_status_history_status', ['new_status', 'created_at'], unique=False)

    op.create_table('job_logs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('job_run_id', sa.String(length=36), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('event_code', sa.String(length=128), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context_json', sa.JSON(), nullable=False),
    sa.Column('trace_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_run_id'], ['job_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_logs', schema=None) as batch_op:
        batch_op.create_index('ix_job_logs_event_code', ['event_code'], unique=False)
        batch_op.create_index('ix_job_logs_job_time', ['job_run_id', 'created_at'], unique=False)
        batch_op.create_index('ix_job_logs_trace_id', ['trace_id'], unique=False)

    op.create_table('artifact_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('prediction_run_id', sa.String(length=36), nullable=True),
    sa.Column('job_run_id', sa.String(length=36), nullable=True),
    sa.Column('artifact_kind', sa.String(length=100), nullable=False),
    sa.Column('logical_name', sa.String(length=300), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=150), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('is_immutable', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(sha256) = 64', name='ck_artifact_files_sha256'),
    sa.CheckConstraint('size_bytes IS NULL OR size_bytes >= 0', name='ck_artifact_files_size'),
    sa.ForeignKeyConstraint(['job_run_id'], ['job_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['prediction_run_id'], ['prediction_runs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_run_id', 'logical_name', name='uq_artifact_files_job_run_name'),
    sa.UniqueConstraint('prediction_run_id', 'logical_name', name='uq_artifact_files_prediction_run_name'),
    sa.UniqueConstraint('storage_path', name='uq_artifact_files_storage_path')
    )
    with op.batch_alter_table('artifact_files', schema=None) as batch_op:
        batch_op.create_index('ix_artifact_files_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_artifact_files_job_kind', ['job_run_id', 'artifact_kind'], unique=False)
        batch_op.create_index('ix_artifact_files_run_kind', ['prediction_run_id', 'artifact_kind'], unique=False)
        batch_op.create_index('ix_artifact_files_sha256', ['sha256'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.String(length=200), nullable=True),
    sa.Column('action', sa.String(length=150), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=200), nullable=False),
    sa.Column('prediction_run_id', sa.String(length=36), nullable=True),
    sa.Column('trace_id', sa.String(length=100), nullable=True),
    sa.Column('before_json', sa.JSON(), nullable=False),
    sa.Column('after_json', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.CheckConstraint("actor_type IN ('user','device','system','codex')", name='ck_audit_logs_actor_type'),
    sa.ForeignKeyConstraint(['prediction_run_id'], ['prediction_runs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_logs_action', ['action', 'occurred_at'], unique=False)
        batch_op.create_index('ix_audit_logs_actor', ['actor_type', 'actor_id', 'occurred_at'], unique=False)
        batch_op.create_index('ix_audit_logs_entity', ['entity_type', 'entity_id', 'occurred_at'], unique=False)
        batch_op.create_index('ix_audit_logs_run', ['prediction_run_id', 'occurred_at'], unique=False)

    op.create_table('ai_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('race_id', sa.String(length=32), nullable=False),
    sa.Column('race_date', sa.Date(), nullable=True),
    sa.Column('prediction_run_id', sa.String(length=36), nullable=True),
    sa.Column('parent_analysis_id', sa.String(length=36), nullable=True),
    sa.Column('analysis_sequence', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('input_data_version', sa.String(length=128), nullable=True),
    sa.Column('input_snapshot_hash', sa.String(length=64), nullable=True),
    sa.Column('input_artifact_id', sa.String(length=36), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('rerun_reason', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('queued','running','succeeded','failed','degraded')", name='ck_ai_analyses_status'),
    sa.CheckConstraint('analysis_sequence > 0', name='ck_ai_analyses_sequence'),
    sa.CheckConstraint('input_snapshot_hash IS NULL OR length(input_snapshot_hash) = 64', name='ck_ai_analyses_input_hash'),
    sa.ForeignKeyConstraint(['input_artifact_id'], ['artifact_files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_analysis_id'], ['ai_analyses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['prediction_run_id'], ['prediction_runs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'analysis_sequence', name='uq_ai_analyses_race_sequence')
    )
    with op.batch_alter_table('ai_analyses', schema=None) as batch_op:
        batch_op.create_index('ix_ai_analyses_prediction_run', ['prediction_run_id'], unique=False)
        batch_op.create_index('ix_ai_analyses_race_created', ['race_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_analyses_race_date'), ['race_date'], unique=False)

    op.create_table('evidence_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('evidence_id', sa.String(length=100), nullable=False),
    sa.Column('prediction_run_id', sa.String(length=36), nullable=False),
    sa.Column('race_id', sa.String(length=32), nullable=False),
    sa.Column('horse_no', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('reliability_grade', sa.String(length=1), nullable=False),
    sa.Column('source_name', sa.String(length=300), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('freshness_status', sa.String(length=30), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('structured_values_json', sa.JSON(), nullable=False),
    sa.Column('impact_hint', sa.String(length=30), nullable=True),
    sa.Column('impact_strength', sa.String(length=30), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('artifact_file_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("impact_hint IS NULL OR impact_hint IN ('positive','negative','neutral')", name='ck_evidence_records_impact_hint'),
    sa.CheckConstraint("reliability_grade IN ('A','B','C','D')", name='ck_evidence_records_reliability'),
    sa.ForeignKeyConstraint(['artifact_file_id'], ['artifact_files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['prediction_run_id'], ['prediction_runs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evidence_id')
    )
    with op.batch_alter_table('evidence_records', schema=None) as batch_op:
        batch_op.create_index('ix_evidence_records_category', ['category', 'reliability_grade'], unique=False)
        batch_op.create_index('ix_evidence_records_fetched_at', ['fetched_at'], unique=False)
        batch_op.create_index('ix_evidence_records_horse', ['race_id', 'horse_no'], unique=False)
        batch_op.create_index('ix_evidence_records_run_race', ['prediction_run_id', 'race_id'], unique=False)

    op.create_table('ai_analysis_outputs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('output_schema_version', sa.String(length=64), nullable=False),
    sa.Column('output_json', sa.JSON(), nullable=False),
    sa.Column('output_hash', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('python_result_visible', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("stage <> 'independent' OR python_result_visible = false", name='ck_ai_analysis_outputs_independent_input'),
    sa.CheckConstraint("stage IN ('independent','comparison','integration')", name='ck_ai_analysis_outputs_stage'),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name='ck_ai_analysis_outputs_confidence'),
    sa.CheckConstraint('length(output_hash) = 64', name='ck_ai_analysis_outputs_hash'),
    sa.ForeignKeyConstraint(['analysis_id'], ['ai_analyses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id', 'stage', name='uq_ai_analysis_outputs_stage')
    )
    with op.batch_alter_table('ai_analysis_outputs', schema=None) as batch_op:
        batch_op.create_index('ix_ai_analysis_outputs_analysis_stage', ['analysis_id', 'stage'], unique=False)

    with op.batch_alter_table('prediction_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config_version_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('feature_weight_version_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('code_version', sa.String(length=200), server_default='unknown', nullable=False))
        batch_op.add_column(sa.Column('parameters', sa.JSON(), server_default=sa.text("'{}'"), nullable=False))
        batch_op.add_column(sa.Column('input_manifest_sha256', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_prediction_runs_config_version_id'), ['config_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_runs_feature_weight_version_id'), ['feature_weight_version_id'], unique=False)
        batch_op.create_foreign_key('fk_prediction_runs_config_version_id', 'config_versions', ['config_version_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key('fk_prediction_runs_feature_weight_version_id', 'feature_weight_versions', ['feature_weight_version_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('bet_candidates', schema=None) as batch_op:
        batch_op.create_check_constraint(
            'ck_bet_candidates_points_nonnegative',
            'points >= 0',
        )
        batch_op.create_check_constraint(
            'ck_bet_candidates_stake_nonnegative',
            'stake_per_point >= 0',
        )
        batch_op.create_check_constraint(
            'ck_bet_candidates_total_nonnegative',
            'total_amount >= 0',
        )
        batch_op.create_check_constraint(
            'ck_bet_candidates_status',
            "status IN ('draft','candidate','review_required','planned','purchased',"
            "'awaiting_result','settled','skipped','cancelled','blocked')",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet_candidates', schema=None) as batch_op:
        batch_op.drop_constraint('ck_bet_candidates_status', type_='check')
        batch_op.drop_constraint('ck_bet_candidates_total_nonnegative', type_='check')
        batch_op.drop_constraint('ck_bet_candidates_stake_nonnegative', type_='check')
        batch_op.drop_constraint('ck_bet_candidates_points_nonnegative', type_='check')

    with op.batch_alter_table('prediction_runs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_prediction_runs_feature_weight_version_id', type_='foreignkey')
        batch_op.drop_constraint('fk_prediction_runs_config_version_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_prediction_runs_feature_weight_version_id'))
        batch_op.drop_index(batch_op.f('ix_prediction_runs_config_version_id'))
        batch_op.drop_column('input_manifest_sha256')
        batch_op.drop_column('parameters')
        batch_op.drop_column('code_version')
        batch_op.drop_column('feature_weight_version_id')
        batch_op.drop_column('config_version_id')

    with op.batch_alter_table('ai_analysis_outputs', schema=None) as batch_op:
        batch_op.drop_index('ix_ai_analysis_outputs_analysis_stage')

    op.drop_table('ai_analysis_outputs')
    with op.batch_alter_table('evidence_records', schema=None) as batch_op:
        batch_op.drop_index('ix_evidence_records_run_race')
        batch_op.drop_index('ix_evidence_records_horse')
        batch_op.drop_index('ix_evidence_records_fetched_at')
        batch_op.drop_index('ix_evidence_records_category')

    op.drop_table('evidence_records')
    with op.batch_alter_table('ai_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_analyses_race_date'))
        batch_op.drop_index('ix_ai_analyses_race_created')
        batch_op.drop_index('ix_ai_analyses_prediction_run')

    op.drop_table('ai_analyses')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_run')
        batch_op.drop_index('ix_audit_logs_entity')
        batch_op.drop_index('ix_audit_logs_actor')
        batch_op.drop_index('ix_audit_logs_action')

    op.drop_table('audit_logs')
    with op.batch_alter_table('artifact_files', schema=None) as batch_op:
        batch_op.drop_index('ix_artifact_files_sha256')
        batch_op.drop_index('ix_artifact_files_run_kind')
        batch_op.drop_index('ix_artifact_files_job_kind')
        batch_op.drop_index('ix_artifact_files_created_at')

    op.drop_table('artifact_files')
    with op.batch_alter_table('job_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_job_logs_trace_id')
        batch_op.drop_index('ix_job_logs_job_time')
        batch_op.drop_index('ix_job_logs_event_code')

    op.drop_table('job_logs')
    with op.batch_alter_table('bet_status_history', schema=None) as batch_op:
        batch_op.drop_index('ix_bet_status_history_status')
        batch_op.drop_index('ix_bet_status_history_bet_time')

    op.drop_table('bet_status_history')
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.drop_index('ix_idempotency_records_resource')
        batch_op.drop_index('ix_idempotency_records_expiry')

    op.drop_table('idempotency_records')
    with op.batch_alter_table('feature_weight_versions', schema=None) as batch_op:
        batch_op.drop_index('ix_feature_weight_versions_created_at')
        batch_op.drop_index('ix_feature_weight_versions_active')

    op.drop_table('feature_weight_versions')
    with op.batch_alter_table('config_versions', schema=None) as batch_op:
        batch_op.drop_index('ix_config_versions_created_at')
        batch_op.drop_index('ix_config_versions_active')

    op.drop_table('config_versions')
    # ### end Alembic commands ###
